config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get "about", to: "pages#about"
  resources :produtos, only: %i[index new create show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/produto.rb
class Produto < ApplicationRecord
  has_one_attached :foto

  validates :nome, :categoria, presence: true
  validates :nome, uniqueness: true
  validates :tamanho, inclusion: { in: %w[S M L], message: "deve ser P, M ou G" }
  # validates :categoria, inclusion: { in: %w[bandeja caixa miniatura outros] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nome, :sobrenome])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  def index
    @products = Produto.all
  end

  def new
    @produto = Produto.new
  end

  def create
    @produto = Produto.new(produtos_params)
    if @produto.save
      redirect_to produto_path(@produto)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @produto = Produto.find(params[:id])
  end

  private

  def produtos_params
    params.require(:produto).permit(:nome, :categoria, :descricao, :tamanho, :disponivel, :foto)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nosso Artesanato</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%# <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<section class="about">
  <h1>Quem somos nós</h1>
  <p>Lorem ipsum erat non maa nunc lacus etiam, dapibus ante nulla diam nisl ut enim. aliquet nunc hac condimentum dui in gravida justo ut aliquam, leo posuere etiam habitant ad elit bibendum habitant vulputate urna, accumsan libero leo elit nostra pulvinar tempus amet. senectus nunc leo blandit porta non risus praesent tristique, sed at fermentum a quisque nibh scelerisque eros leo, arcu aliquam tempus ultrices class hac nulla. ad torquent pretium morbi metus egestas ligula consequat iaculis, felis tellus etiam quam facilisis donec nisl erat volutpat, purus imperdiet diam turpis ad vivamus mauris.</p>
  <p>Fringilla habitasse sapien aliquam imperdiem tempus fusce turpis sagittis, ipsum posuere ligula semper massa rutrum. imperdiet integer lectus senectus auctor cras neque dictumst cras, ultrices quis nullam euismod nisl et eleifend, lacus pretium tempor est potenti neque netus. eget ornare eros nulla turpis rutrum ornare massa varius, elit eget ut hendrerit nisi pharetra luctus senectus, ante euismod lobortis velit etiam ligula potenti. sociosqu arcu enim nunc euismod praesent velit ante quam sagittis tempus, quis vulputate sagittis pharetra platea litora id egestas sit libero, nulla pulvinar risus vulputate imperdiet habitant tempus lorem vestibulum. </p>

</section>

app/views/pages/home.html.erb
<section class="banner">
  <div class="photos">
    <div class="photo"></div>
  </div>
  <div class="banner-text">
    <div class="top">
      <h1>Bem vindo <br>ao <br>Nosso Artesanato</h1>
    </div>
    <div class="bottom">
      <p>Onde a criatividade não tem limites.</p>
      <%= link_to "Ver Peças", produtos_path, class:"buttom"%>
    </div>
  </div>


</section>






<%= link_to "Bandejas", "#" %>
<%= link_to "Caixas", "#" %>
<%= link_to "Minuaturas", "#" %>
<%= link_to "Outros", "#" %>

app/views/produtos/edit.html.erb
<h1>Produtos#edit</h1>
<p>Find me in app/views/produtos/edit.html.erb</p>

app/views/produtos/index.html.erb
<div class= "container mt-5">
  <div class= "produtos-cards">
    <% @products.each do |produto| %>
      <%= render "shared/card", produto: produto %>
    <% end %>
  </div>
</div>

app/views/produtos/new.html.erb
<h1>Produtos new</h1>

<%= simple_form_for @produto do |f| %>
  <%= f.input :nome %>
  <%= f.input :categoria, collection: %i[bandeja caixa miniatura outros] %>
  <%= f.input :descricao %>
  <%= f.input :tamanho, collection: %i[S M L] %>
  <%= f.input :disponivel %>
  <%= f.input :foto, as: :file %>

  <%= f.submit %>
<% end %>

app/views/produtos/show.html.erb
<div class="produto-container">
  <div class="produto">
    <h2><%= @produto.nome %></h2>
    <%= cl_image_tag @produto.foto.key, height: 300, width: 300, crop: :fill %>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card-produto">
  <%= cl_image_tag produto.foto.key, height: 300, width: 300, crop: :fill, class: "produto-img" %>
  <div class="card-infos">
    <h2 class="produto-name"><%= produto.nome %></h2>
    <i class="fa-regular fa-heart favorite-icon"></i>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<section id="navbar">
  <div class="left">
    <p class="logo">Nosso Artesanato</p>
  </div>
  <div class="right">
    <div class="menu">
      <%= link_to "HOME", root_path, class:"menu-item" %>
      <%= link_to "ABOUT", about_path, class:"menu-item" %>
      <%= link_to "PRODUTOS", produtos_path, class:"menu-item" %>
      <% if user_signed_in? %>
        <%= link_to '#', class:"menu-item-last" do %>
          <i class="fa-solid fa-user"></i>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path, class:"menu-item-last" do %>
          <i class="fa-solid fa-user"></i>
        <% end %>
      <% end %>
      <%# <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
    </div>
  </div>
</section>

app/views/shared/_navbar2.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>